Vagrant.configure(2) do |config|
  config.vm.box = "janihur/ubuntu-1604-lxde-desktop"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 1024
  end

  config.vm.define "prod" do |prod|
    prod.vm.network "private_network", ip: "192.168.33.10"
    prod.vm.provision "shell", path: "provision_prod.sh"
  end

  config.vm.define "dev" do |dev|
    dev.vm.network "private_network", ip: "192.168.33.11"
    dev.vm.provision "shell", path: "provision_dev.sh"
  end
end
